server:
  port: 8760

spring:
  application:
    name: client
  #thymelea模板配置
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: http://localhost:8760
    prefer-ip-address: true
ribbon:
  eureka:
    enable: true

