server:
  port: 8760

spring:
  application:
    name: client
  #thymelea模板配置
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.37.30.244:3306/friends?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    #url: jdbc:mysql://localhost:3306/login?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    #password: root
    password: dfc77

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://121.37.30.244:8761/eureka/
  instance:
    #instance-id: http://localhost:8760
    instance-id: http://121.37.30.244:8760
    prefer-ip-address: true
ribbon:
  eureka:
    enable: true

mybatis:
  mapperLocations: classpath:/mapper.xml
  typeAliasesPackage: com.imooc.javabean
centos:
  path: /home/uploadFile/
  #path: E:\\exercise\\
  copyFileDesPath: /home/copyFile/222.txt

